### ISSUE TITLE
Color Coding is different from Brackets editor

### ISSUE THREAD

**Issue by aahoo** [peterflynn/copy-as-html#2]
Thanks for the great extension :)
A minor issue or feature:
Why is the color coding of the generated HTML different from color coding seen in Brackets editor?
Example:
Comments look grey in the editor while they are orange in the the generated HTML.

**Comment by peterflynn** [comment]
Yikes, sorry for missing that!  The new theming feature in Brackets 0.42 broke the coloring.  Fixed in version 1.0.5
