### ISSUE TITLE
Not pasting into Word

### ISSUE THREAD

**Issue by danielmoi** [peterflynn/copy-as-html#5]
I'm having no luck pasting into Word.
I've installed the extension, but it just pastes as unformatted text - without even an option for formatted text in Word.
Am I missing something here?
Thanks!

**Comment by peterflynn** [comment]
@dm4000 Are you using the Edit > Copy as HTML menu item, or just regular Copy?  Note that there are two different commands.

**Comment by danielmoi** [comment]
Thank you!!!!
That completely worked, and I love it.  Such a great extension, thank you very much again!

**Comment by peterflynn** [comment]
@dm4000 Thanks, glad you're finding it useful!
